### ISSUE TITLE
请问每篇博文封面在那边修改

### ISSUE THREAD

**Issue by raighnew** [foru17/nevecoo#7]

**Comment by foru17** [comment]
你说的封面，是哪一张？背景图的还是？

**Comment by raighnew** [comment]
发一篇没有照片的博文，主页上这篇博文的默认封面是你云端的一张照片（飞机上落日的那张），如果博文中有我自己的照片，我怎么样才能设置自己的照片为封面
发自翁浩

**Comment by raighnew** [comment]
给img加上cover-image，还是不能在首页显示

**Comment by lebensterben** [comment]
把那个照片放在文首似乎可以解决你的问题
